### ISSUE TITLE
Allow other browsers to be used in cookie generation

### ISSUE THREAD

**Issue by xtream1101** [xtream1101/humblebundle-downloader#7]

**Comment by cenodis** [comment]
Is there a specific reason why this program uses a custom format instead of the standard Netscape Cookie Format? There are many extension for most browsers that export to this and its the de facto standard to exchange cookies. This would also eliminate the need to have a custom script to export cookies.

I havent tried loading such a format with Python but according to the docs `http.cookiejar` is able to parse it and uses the Netscape format by default.

[Doc of http.cookiejar](https://docs.python.org/3/library/http.cookiejar.html)
[Description of the Netscape Cookie Format](http://www.cookiecentral.com/faq/#3.5)
